### ISSUE TITLE
UnicodeEncodeError downloading problem 5 on Python 2

### ISSUE THREAD

**Issue by jayvdb** [ewjoachim/pyler#4]
```
$ pyler gen 5
Traceback (most recent call last):
  File "/usr/bin/pyler", line 9, in <module>
    load_entry_point('pyler==0.1.1', 'console_scripts', 'pyler')()
  File "/usr/lib/python2.7/site-packages/pyler-0.1.1-py2.7.egg/pyler/__main__.py", line 178, in main
    args.pop("callback")(**args)
  File "/usr/lib/python2.7/site-packages/pyler-0.1.1-py2.7.egg/pyler/__main__.py", line 118, in gen_files
    doc=doc,
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd7' in position 132: ordinal not in range(128)
```

No such problem on Python 3 ;-)

**Comment by ewjoachim** [comment]
Hello,

Yes, the development was done with Python 3, and I haven't really tried Python 2. I think that it shouldn't be too complex to make the package fully compatible, using [six](https://pypi.python.org/pypi/six) for the compatibility and [tox](https://pypi.python.org/pypi/tox) to have the tests run on both versions.

Are you interested in taking part in this ? If so, I can help :) I'll do my best, but I can't promise I'll find the time to fix it by myself, though.

BTW, I'm glad that this project was useful for anyone else than me. I you want to send me some feedback, please feel free. Did it work for the problems 1 to 4 ? Are there key features missing ?
